{{- $_ := include "prometheus-rw.server-url" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}-deployment
  labels:
    app.kubernetes.io/name: {{ .Values.global.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.global.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.global.name }}
    spec:
      containers:
      - name: {{ .Values.global.name }}
        image: {{ include "deployment.image" . }}
        ports:
        - containerPort: {{ .Values.global.metricsPort }}
        
        env:
{{- range $key, $value := .Values.deployment.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
{{- end }}

{{- if .Values.global.prometheusRW -}}
{{- range $key, $value := .Values.deployment.envRW }}
        - name: {{ $key }}
          value: {{ $value | quote }}
{{- end }}

{{- $root := . }}
{{- range $key, $value := .Values.deployment.secretEnvRW }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $root.Values.global.name }}-secret
              key: {{ $key }}
{{- end }}
{{- end }}

        # Expose Pod Information to Containers Through Environment Variables
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
