####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
# It uses a micro base image, tuned for Quarkus native executables.
# It reduces the size of the resulting container image.
# Check https://quarkus.io/guides/quarkus-runtime-base-image for further information about this image.
#
# Before building the container image run:
#
# ./mvnw package -Dnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.jvm.native-micro -t quarkus/micrometer-quickstart .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/micrometer-quickstart
#
###
FROM quay.io/quarkus/quarkus-micro-image:2.0@sha256:c938fe59e3cb10163ffc1783357bbf3207d20a07c7e0a71e5ac7621de1d86bb5
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
