{{- if and .Values.cleaner.enabled .Values.privilegedRights }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.cleaner.serviceAccount.name }}-crole
  labels:
    {{- if .Values.cleaner.serviceAccount.annotations }}
    {{- toYaml .Values.cleaner.serviceAccount.annotations | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterrolebindings
      - clusterroles
    verbs:
      - list
      - delete
{{- end }}
