version: '3'

services:

  # DATABASES
  postgres:
    image: postgres:15.3-alpine@sha256:4ca65a9209f164bdb30f715ac2ed9182cc0737d0f0a549031b3c1b0b7e652f3a
    container_name: ${PG_CONTAINER_NAME:-postgres}
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - PG_CONTAINER_NAME=${PG_CONTAINER_NAME:-postgres}
      - PG_TEST_USER=${PG_TEST_USER:-test}
      - PG_TEST_USER_PASSWORD=${PG_TEST_USER_PASSWORD:-test}
      - PG_TEST_DATABASE=${PG_TEST_DATABASE:-cdt_test}
    ports:
      - "5432:5432"
    volumes:
     - ${PG_INIT_PATH:-./postgres/init}:/docker-entrypoint-initdb.d

  postgres_db:
    image: postgres:latest@sha256:b6b4d0b75c699a2c94dfc5a94fe09f38630f3b67ab0e1653ede1b7ac8e13c197
    hostname: postgres-db
    container_name: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # Set a strong password
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ../src/main/resources/persistence/cloud.init_db.sql:/docker-entrypoint-initdb.d/schema.sql


  minio:
    image: minio/minio:latest@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API port
      - "9001:9001"  # MinIO UI port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  # OBSERVABILITY

  prometheus:
    image: prom/prometheus:latest@sha256:1f0f50f06acaceb0f5670d2c8a658a599affe7b0d8e78b898c1035653849a702
    container_name: prometheus
    ports:
      - "9090:9090"

  node-exporter:
    image: prometheus/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana:latest@sha256:e932bd6ed0e026595b08483cd0141e5103e1ab7ff8604839ff899b8dc54cabcb
    container_name: grafana
    ports:
      - "3000:3000"

  jaeger:
    image: jaegertracing/all-in-one:latest@sha256:ab6f1a1f0fb49ea08bcd19f6b84f6081d0d44b364b6de148e1798eb5816bacac
    container_name: jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"
      - "14250:14250"
      - "16686:16686"

volumes:
  postgres_db:
    driver: local
