{{- if and .Values.maintenanceJob.migrateSchema.enabled .Values.maintenanceJob.migrateSchema.serviceAccount.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.maintenanceJob.migrateSchema.serviceAccount.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    {{- if .Values.maintenanceJob.migrateSchema.serviceAccount.annotations }}
    {{- toYaml .Values.maintenanceJob.migrateSchema.serviceAccount.annotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.namedLabels" .Values.maintenanceJob.migrateSchema | nindent 4 }}
    {{- include "common.commonLabels" . | nindent 4 }}
{{- end }}
