apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: monitoring
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Values.name }}
          image: {{ template "quarkus-3-vertx.image" . }}
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: CLOUD_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: MICROSERVICE_NAME
              value: {{ .Values.name }}
            {{- if .Values.extraEnvs }}
              {{- toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
