apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/component: monitoring
  name: {{ .Values.name }}
spec:
  type: NodePort
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: web
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
