{{- if .Values.maintenanceJob.serviceAccount.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.maintenanceJob.serviceAccount.name }}
  annotations:
    {{- toYaml .Values.maintenanceJob.serviceAccount.annotations | nindent 4 }}
  labels:
    {{- include "common.namedLabels" .Values.maintenanceJob | nindent 4 }}
    {{- include "common.commonLabels" . | nindent 4 }}
{{- end }}
