apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.name }}-secret
type: Opaque
stringData:
{{- range $key, $value := .Values.deployment.secretEnvRW }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
